<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import legal from '@/content/legal.json'

/**
 * One view, three routes (terms/eula/agreement) — same rendering, different
 * slug. Content comes from content/legal.json, generated by
 * scripts/legal_to_json.py against the live site's actual pages, so this
 * never has hand-retyped legal text drifting from the real Service
 * Agreement / Terms / EULA.
 */
const route = useRoute()
const doc = computed(() => legal[route.meta.legalSlug])
</script>

<template>
  <section class="shell legal-doc py-16 md:py-20" v-if="doc">
    <p v-if="doc.eyebrow" class="label text-rust">{{ doc.eyebrow }}</p>
    <h1 class="display-2 mt-4 max-w-3xl text-ink">{{ doc.title }}</h1>
    <p v-if="doc.updated" class="mt-4 text-[14px] text-ink-2">{{ doc.updated }}</p>

    <div class="mt-10 max-w-[68ch] space-y-5">
      <template v-for="(block, i) in doc.blocks" :key="i">
        <h2 v-if="block.type === 'h2'" class="display-3 mt-10 text-ink">
          {{ block.text }}
        </h2>
        <h3 v-else-if="block.type === 'h3'" class="mt-6 text-[17px] font-bold text-ink">
          {{ block.text }}
        </h3>
        <ul v-else-if="block.type === 'ul'" class="list-disc space-y-2 pl-5 text-[16px] leading-relaxed text-ink-2">
          <li v-for="(item, j) in block.items" :key="j">{{ item }}</li>
        </ul>
        <p v-else class="text-[16px] leading-relaxed text-ink-2">{{ block.text }}</p>
      </template>
    </div>
  </section>
</template>
